Web_ban_hang/Controllers/GioHangController.cs
using Common;
using Model.Dao;
using Model.EF;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web_ban_hang.Models;

namespace Web_ban_hang.Controllers
{
    public class GioHangController : Controller
    {
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            var user = (UserLogin)Session[Web_ban_hang.Common.CommonConstants.USER_SESSION];            
            if (cart != null)
            {                
                list = (List<CartItem>)cart;               
            }
            else
            {
                if (user != null)
                {
                    var cartserver = new GioHangDao().Listall(user.UserName);
                    if (cartserver.Count > 0)
                    {                        
                        var danhsach = (List<CartItem>)Session[CartSession];
                        foreach (var item in cartserver)
                        {
                            var cartiem = new CartItem();                            
                            cartiem.sanpham = item.SanPham;
                            cartiem.Quantity = item.soluong;
                            cartiem.check = false;
                            cartiem.ID = item.ID_GH;
                            cartiem.MaKV = item.MaKV;
                            if (danhsach!=null)
                            {
                                foreach (var item1 in danhsach)
                                {
                                    if (item1.sanpham.MaSP != item.MaSP)
                                    {
                                        list.Add(cartiem);
                                    }                                  
                                }
                            }
                            else
                            {
                                list.Add(cartiem);
                            }                           
                        }                        
                        Session[CartSession] = list;                       
                    }
                }
            }            
            return View(list);
        }

        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.sanpham.MaSP == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.sanpham.MaSP == item.sanpham.MaSP);
                if (jsonItem != null)
                {
                    if (item.sanpham.soluong >= jsonItem.Quantity)
                    {
                        item.Quantity = jsonItem.Quantity;
                    }
                    else
                    {
                        return Json(new
                        {
                            status = false
                        });
                    }                   
                    
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public ActionResult AddItem(int productId, int quantity)
        {
            var product = new NewDao().ViewDetail(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.sanpham.MaSP == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.sanpham.MaSP == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //tạo mới đối tượng cart item
                    var item = new CartItem(); 
                    item.sanpham = product.SanPham;
                    item.Quantity = quantity;
                    item.check = false;
                    item.MaKV = product.MaKV;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //tạo mới đối tượng cart item
                var item = new CartItem();
                item.sanpham = product.SanPham;
                item.Quantity = quantity;
                item.check = false;
                item.MaKV = product.MaKV;
                var list = new List<CartItem>();
                list.Add(item);
                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            var session = (UserLogin)Session[Web_ban_hang.Common.CommonConstants.USER_SESSION];
            ViewBag.user = new UserDao().GetById(session.UserName);
            if (cart != null)
            {
                foreach (var item in (List<CartItem>)cart)
                {
                    if (item.check)
                    {
                        var item1 = new CartItem();
                        item1.sanpham = item.sanpham;
                        item1.Quantity =item.Quantity;
                        item1.check = true;
                        list.Add(item1);
                    }
                }
                

            }
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var session = (UserLogin)Session[Web_ban_hang.Common.CommonConstants.USER_SESSION];
            try
            {                
                var cart = (List<CartItem>)Session[CartSession];                              
                decimal total = 0;
                foreach (var item in cart)
                {
                    if (item.check)
                    {
                        var gioHang = new GioHang();
                        gioHang.MaSP = item.sanpham.MaSP;
                        gioHang.date = DateTime.Now;
                        gioHang.Gia = item.sanpham.GiaBan;
                        gioHang.soluong = item.Quantity;
                        gioHang.UserID = session.UserID;
                        gioHang.ID_GH = item.ID;
                        gioHang.MaKV = item.MaKV;
                        new GioHangDao().insertdonhang(gioHang, shipName, mobile, address, email);
                        new NewDao().updateSL(item.sanpham.MaSP, item.Quantity);                       
                    }

                }
                
                string content = null;
                foreach (var item in cart)
                {
                    if (item.check)
                    {
                        total += (item.sanpham.GiaBan.GetValueOrDefault(0) * item.Quantity);
                        content = content + "<tr>" +
                                 "<td>" + item.sanpham.MaSP + "</td>" +
                                 "<td>" + item.sanpham.TenSP + "</td>" +
                                 "<td><img src='https://fptshop.com.vn/Uploads/images/2015/Tin-Tuc/MinhHieu/huong-dan-cach-tao-link-download-truc-tiep-tu-google-driver-1.png' width='100' /></td>" +
                        "<td>" + item.Quantity + "</td>" +
                                 "<td>" + total + "</td>" +
                             "</tr>";                        
                    }
                }
                for (int i = 0; i < cart.Count; i++)
                {
                    if (cart[i].check)
                    {
                        cart.Remove(cart[i]);
                    }
                }
                string body = "<!DOCTYPE html>" +
                            "<html>" +
                            "<head>" +
                               "<meta name='viewport' content='width = device - width' />" +
                                "<title>Thông tin đơn hàng mới từ khách hàng:" + shipName + "</title>" +
                            "</head>" +
                            "<body>" +
                            "<b>ĐÂY LÀ EMAIL TỰ ĐỘNG</b> <br />" +
                                 "Thông tin đơn hàng mới từ khách hàng: " + shipName + "<br />" +
                                "Điện thoại: " + mobile + " <br />" +
                                "Email: " + email + "<br />" +
                                "Địa chỉ: " + address + "<br />" +
                                "<div class='content'>" +
                                "<div class='section group'>" +
                                    "<table class='table'>" +
                                            "<thead>" +
                                                "<tr>" +
                                                    "<td>Số Thứ Tự</td>" +

Web_ban_hang/Views/GioHang/Index.cshtml
@model List<Web_ban_hang.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section jsFooter{
    <script src="/assets/client/js/controller/cartController.js"></script>
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table" id="datagioH">
                <thead>
                    <tr>
                        <td>Chọn</td>
                        <td>STT</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr id="@Model[i].sanpham.MaSP">
                            <td><input type="checkbox" id="check_@(i+1)" /></td>
                            <td>@(i+1)</td>
                            <td>@Model[i].sanpham.TenSP</td>
                            <td><img src="@Model[i].sanpham.AnhTDe" width="100" /></td>
                            <td><input type="text" class="txtQuantity" data-id="@Model[i].sanpham.MaSP" value="@Model[i].Quantity" /></td>
                            <td>@Model[i].sanpham.GiaBan.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((Model[i].sanpham.GiaBan.GetValueOrDefault(0) * Model[i].Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@Model[i].sanpham.MaSP" class="btn-delete">Xoá</a></td>
                        </tr>
                    }
                    
                </tbody>
            </table>
            <div>
                <div class="menu">
                    <button id="btnContinue" class="btn">Tiếp tục mua hàng</button>
                    <button id="btnUpdate" class="btn">Cập nhật giỏ hàng</button>
                    <button id="btnDeleteAll" class="btn">Xoá giỏ hàng</button>
                    <button id="btnPayment" class="btn">Thanh toán</button>
                </div>                
                <div class="an"><b>Tổng tiền:</b> <span id="tong_tien" style="left:5px">0</span> <b style="left:5px"> Đồng</b> </div>
            </div>
            
        }
        else
        {
            <span class="alert alert-danger">Chưa có sản phẩm nào trong giỏ hàng</span>
        }
    </div>
</div>

Web_ban_hang/Views/GioHang/Payment.cshtml
@model List<Web_ban_hang.Models.CartItem>
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section jsFooter{

    <script src="~/assets/client/js/controller/giohangController.js"></script>
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table" id="datagioH">
                <thead>
                    <tr>
                        <td>STT</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@Model[i].sanpham.TenSP</td>
                            <td><img src="@Model[i].sanpham.AnhTDe" width="100" /></td>
                            <td>@Model[i].Quantity</td>
                            <td>@Model[i].sanpham.GiaBan.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((Model[i].sanpham.GiaBan.GetValueOrDefault(0) * Model[i].Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@Model[i].sanpham.MaSP" class="btn-delete">Xoá</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="an"><b>Tổng tiền:</b> <span id="tong_tien" style="left:5px">0</span> <b style="left:5px"> Đồng</b> </div>
        }
    </div>
    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Payment", "GioHang", FormMethod.Post))
            {
                var user = (Model.EF.Taikhoan)ViewBag.user;
                if (user != null)
                {
                    <div class="form-group">
                        <label>Người nhận</label>
                        <input name="shipName" class="form-control" value="@user.HovaTen" />
                    </div>
                    <div class="form-group">
                        <label>Điện thoại</label>
                        <input name="mobile" class="form-control" value="@user.Phone" />
                    </div>
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <input name="address" class="form-control" value="@user.DiaChi" />
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input name="email" class="form-control" value="@user.Email" />
                    </div>
                    <button type="submit" class="btn">Gửi đơn hàng</button>
                }

            }
        </div>

    </div>
</div>

Web_ban_hang/Views/GioHang/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="alert alert-success">
    Bạn vừa mua hàng thành công.
</div>